# Generated by Django 4.2.5 on 2023-10-03 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_alter_cartitem_cart'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SHIPPED'), ('D', 'DELIVERED')], default='P', max_length=1)),
                ('payment_status', models.CharField(choices=[('P', 'PAYED'), ('N', 'NOTPAYED'), ('S', 'ONDELIVERY')], default='N', max_length=1)),
                ('address', models.CharField(max_length=550)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop.product')),
            ],
        ),
    ]
